### ISSUE TITLE
Unknown 'gray2' in multiple components

### ISSUE THREAD

**Issue by selrond** [jxnblk/rebass#322] opened 2017-08-31 14:18 UTC
I've noticed there's invalid color `gray2` set on [multiple components](https://github.com/jxnblk/rebass/blob/master/src/components.js) (Input, Select, Textarea, Slider, Border, Card, Progress, Tabs) `background-color`s and `box shadow`s set by default.  Thus the intended properties don't render.

A sample code from my page:
```css
.iUtigF {
	font-family: inherit;
	line-height: inherit;
	display: inline-block;
	vertical-align: middle;
	border: 0;
	box-shadow: inset 0 0 0 1px gray2;
	border-radius: 25px;
	-webkit-appearance: none;
	-moz-appearance: none;
	appearance: none;
	text-align: center;
	font-weight: 400;
}
```

**Comment by mannie-faux** [comment] 2017-09-20 01:32
Similar issue here. Just noticed it with the `Card` component. Have you noticed it with any color other than `gray2`?

**Comment by selrond** [comment] 2017-09-20 03:56
@mannie-faux nope, just `gray2` seems to be a problem

**Comment by epilande** [comment] 2017-09-22 17:10
@selrond @mannie-faux this is because the components don't have the theme context.
 
Rebass has a `<Provider />` component that will properly configure the theme, just need to use it at the root of your application. 

See http://jxnblk.com/rebass/theming.

**Comment by mannie-faux** [comment] 2017-09-24 01:19
I don't really have this "issue" anymore as I'm not really using the same components much at the moment, but I wanted to point out that I already had the Provider with a theme wrapping my app when I posted that comment.
```js
<Rebass.Provider theme={theme}>
    {props.children}
</Rebass.Provider>
```
with a theme setup like so:
```js
import colors from './colors';

export default {
  colors,
  font: '"Open Sans", -apple-system, BlinkMacSystemFont, sans-serif',
  monospace: 'Inconsolata, "SF Mono", "Roboto Mono", Menlo, monospace',
  radius: 0,
};
```
The `gray2` color is definitely present and accessible as `colors.gray[2]`, but I'm not sure how to works with the `gray2` color being referenced in the Rebass component definition itself.

Oh, and my `colors` variable is just a custom color palette I made using `palx`.

**Comment by epilande** [comment] 2017-09-24 04:18
@mannie-faux Ah `palx` returns an array of grays, that's why you're able to access it with `colors.gray[2]`, but rebass looks for `colors.gray2`. The array needs to be flattened onto the colors object.

Rebass also use `palx` to generate colors then flattens it to a single colors object. https://github.com/jxnblk/rebass/blob/29701cbd394925d9d4b1f69d7d9a0b34cf69df3a/src/theme.js#L38-L59

**Comment by mannie-faux** [comment] 2017-09-24 05:49
Oh duh. I took Rebass using `palx` too literally, and I figured the answer was something similar to this! Thanks for the help, this should probably fix a lot of styling errors that I probably never even realised were there.

What about you @selrond? Was the lack of `Provider` the issue?

**Comment by selrond** [comment] 2017-09-25 05:55
@mannie-faux @epilande I have properly used theme provider in the root of my app, the problem still persists.

**Comment by epilande** [comment] 2017-09-25 06:21
@selrond does the theme prop get propagated down to your styled components? When the theme prop reaches those components you mentioned (`Input`, `Select`, `Textarea`, `Slider`, etc..), how does the colors object look?

**Comment by mannie-faux** [comment] 2017-09-25 06:23
@selrond Hmm. Well, the problem personally occurred due to me not flattening the Palx-generated palette prior to passing it into the Rebass theme. The error suggests that your own theme is being passed an incorrectly-formatted `color` object as well or one that is missing. Does the component that actually has that bad CSS actually have the theme/colors as props in React Dev Tools? Could you share your repo, and if not, just some affected code?

**Comment by brandonmp** [comment] 2017-11-20 22:59
for me, the cause of confusion was [this example](http://jxnblk.com/rebass/theming):


>The theme object has the following shape. Any custom values passed to the Provider component will be merged with the defaults.
```
// Default values
const theme = {
  breakpoints: [
    32,
    48,
    64,
    80
  ],
  space: [
    0,
    4,
    8,
    16,
    32,
    64,
    128,
  ],
  fontSizes: [
    12,
    14,
    16,
    20,
    24,
    32,
    48,
    64,
    72,
    96
  ],
  weights: [
    400,
    700
  ],
  colors: {
    black: '#000',
    white: '#fff',
    ...palxColors       <--  wat
  },
  radius: 4,
  font: '-apple-system, BlinkMacSystemFont, sans-serif',
  monospace: '"SF Mono", "Roboto Mono", Menlo, monospace'
}
```

@epilande 's snip was perfect though

**Comment by jxnblk** [comment] 2018-06-10 23:44
Closing this since palx has been removed in v2

**Closed by jxnblk** 2018-06-10 23:44 UTC
