### ISSUE TITLE
Custom theme is not being merged with the defaults

### ISSUE THREAD

**Issue by sarneeh** [jxnblk/rebass#464] opened 2018-08-31 15:34 UTC
The [docs](http://jxnblk.com/rebass/theming) state that: **Any custom values passed to the Provider component will be merged with the defaults.**. But this is completely not true and totally misleading.

I've just looked fast in the code and I guess I'm right:

https://github.com/jxnblk/rebass/blob/2d0ebd34ad865d35deb5b57b08707fadf851c3f1/src/Provider.js#L14

This does not **merge** the objects, instead it **overwrites** every default theme property you add to your custom theme. Using something like [lodash merge](https://lodash.com/docs/4.17.10#merge) method would create the proper behavior.

**Comment by jxnblk** [comment] 2018-08-31 18:38
This is a flat merge, not a deep merge

Duplicate of #388

**Closed by jxnblk** 2018-08-31 18:38 UTC

**Comment by sarneeh** [comment] 2018-08-31 21:12
@jxnblk Well, that's obvious to you because you wrote it. I guess the documentation could be improved in this case 😄
