### ISSUE TITLE
Unknown prop `bg` on <div> tag

### ISSUE THREAD

**Issue by craig-mulligan** [jxnblk/rebass#299] opened 2017-08-07 14:27 UTC
Passing `bg` prop to `Box` results in prop being passed to underlying `<div>`.
```
<Box bg="gray" />
```

Does this relate to #266 whitelisting issues?

**Comment by jxnblk** [comment] 2017-08-10 12:38
Yes, this is a duplicate of #266 - I hope to have a better solution to this at some point soon

**Closed by jxnblk** 2017-08-10 12:38 UTC
