### ISSUE TITLE
weird behavior with Carousel

### ISSUE THREAD

**Issue by jacobhausler** [jxnblk/rebass#337] opened 2017-10-01 22:01 UTC
I'm using Rebass to build a dashboard, and have a Flex of items wrapped in Border elements. It's going great! You've built the best functional component library out there.

But, when I c&p  the Carousel example from the storybook (including hoc(),the Buttons, etc), I'm seeing weird behavior during slide transition. 

See below for screenshots of the behavior. The slides don't seem to be transitioning far enough, with the deficit building up with successive slides.

This behavior is consistent when using a brand new empty create-react-app and rendering the copy and pasted Live component from the storybook inside a Provider. See below for an App.js that demonstrates. 

![image](https://user-images.githubusercontent.com/12172804/31059978-5e8f4422-a6d0-11e7-8b80-fbe457f5be8d.png)

Looks good.

![image](https://user-images.githubusercontent.com/12172804/31059981-69a27abe-a6d0-11e7-8360-3b8c307d5a24.png)

D: 

![image](https://user-images.githubusercontent.com/12172804/31059983-748affdc-a6d0-11e7-8af5-fecd8987f2e0.png)

D: D:

Any ideas? 

Also, do you have any advice for the simplest way to put Carousel's increment on an Interval?

Thank you!

```
import React, { Component } from 'react';
import { createProvider } from 'refunk'
import {
  Provider,
  Carousel,
  Box,
  CarouselSlide,
  Heading,
  Relative,
  Absolute,
  Button,
} from 'rebass'

const hoc = createProvider({ index: 0 })
const inc = state => ({ index: state.index + 1 })
const dec = state => ({ index: state.index - 1 })

const Live = hoc(props => (
  <Relative>
    <Carousel index={props.index % 3}>
      <CarouselSlide
        py={6}
        bg='gray'>
        <Heading>Hello</Heading>
      </CarouselSlide>
      <CarouselSlide
        py={6}
        color='white'
        bg='blue'>
        <Heading>Hello</Heading>
      </CarouselSlide>
      <CarouselSlide
        py={6}
        color='white'
        bg='green'>
        <Heading>Hello</Heading>
      </CarouselSlide>
    </Carousel>
    <Absolute right bottom>
      <Button
        m={2}
        onClick={e => props.update(dec)}
        children='Back'
      />
      <Button
        m={2}
        onClick={e => props.update(inc)}
        children='Next'
      />
    </Absolute>
  </Relative>
))

class App extends Component {
  render() {
    return (
        <Provider>
            <Box p={3}>
                <Live/>
            </Box>
        </Provider>
    );
  }
}

export default App;
```

**Comment by macklinu** [comment] 2018-04-21 00:37
Did you get this resolved? I modified your example using the latest versions of refunk, rebass, and react, and am unable to reproduce your original issue.

```js
import React from "react";
import * as ReactDOM from "react-dom";
import { connect } from "refunk";
import {
  Provider,
  Carousel,
  Box,
  Flex,
  Heading,
  Relative,
  Absolute,
  Button
} from "rebass";

const inc = state => ({ index: state.index + 1 });
const dec = state => ({ index: state.index - 1 });

/**
 * No longer provided by Rebass 2.0.0-0.
 * Taken from http://jxnblk.com/rebass/components/Carousel.
 */
const CarouselSlide = ({ children, ...props }) => (
  <Box {...props}>
    <Flex p={6} justify="center" align="center" children={children} />
  </Box>
);

const Live = connect(props => (
  <Relative>
    <Carousel index={Math.abs(props.index % 3)}>
      <CarouselSlide py={6} bg="gray">
        <Heading>Slide 1</Heading>
      </CarouselSlide>
      <CarouselSlide py={6} color="white" bg="blue">
        <Heading>Slide 2</Heading>
      </CarouselSlide>
      <CarouselSlide py={6} color="white" bg="green">
        <Heading>Slide 3</Heading>
      </CarouselSlide>
    </Carousel>
    <Absolute right={0} bottom={0}>
      <Button m={2} onClick={() => props.update(dec)} children="Back" />
      <Button m={2} onClick={() => props.update(inc)} children="Next" />
    </Absolute>
  </Relative>
));

const App = connect(props => (
  <Provider>
    <Box p={3}>
      <Live />
    </Box>
  </Provider>
));

const initialState = { index: 0 };

ReactDOM.render(<App {...initialState} />, document.getElementById("root"));
```

Explore the Codesandbox to play around with the code if you're interested.

[![Edit pm79oy626j](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/pm79oy626j)

**Comment by jxnblk** [comment] 2018-06-10 23:50
Closing this since v2 is a rewrite. Please open a new issue if this hasn't been resolved

**Closed by jxnblk** 2018-06-10 23:50 UTC
