### ISSUE TITLE
Error using Text component for production.

### ISSUE THREAD

**Issue by johnkmzhou** [jxnblk/rebass#364] opened 2018-02-09 15:39 UTC
When using the [Text](http://jxnblk.com/rebass/components/Text) component and creating a production build, it causes the error: 
```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```
https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=object&args[]=

**Comment by jxnblk** [comment] 2018-02-09 15:46
This sometimes happen if the Text component isn't imported in the module and React is receiving the global [`Text`](https://developer.mozilla.org/en-US/docs/Web/API/Text) instead. Do you have `import { Text } from 'rebass'` in scope in your module?

**Comment by johnkmzhou** [comment] 2018-02-09 22:56
Sorry about that, I made a mistake in my initial attempt to recreate the problem. What's really happening is when I pass Text into a styled HOC, it gets rendered in development but not in production. It appears to lose all stylings in production. This has actually forced us to run production builds with Webpack set to NODE_ENV=development for the time being and has caused other unusual issues.

Here's some example code:
```
import React, { Component } from 'react';
import { Text } from 'rebass';
import styled from 'styled-components';

const ColorText = styled(Text) `
  color: pink;
`;

class App extends Component {
  render() {
    return (
      <div className="App">
        <ColorText>Hello</ColorText>
      </div>
    );
  }
}

export default App;
```
If you also want an example repo, I can create a create-react-app showing the issue.

**Comment by trabek** [comment] 2018-03-07 06:44
check the link below, I had similar problem whit grid-styled. In my case grid-styled had different version of styled-components than the styled-components itself. And as a result the styles were not applied in production but worked in development. It almost drove me crazy before I solved it 

https://www.styled-components.com/docs/faqs#why-am-i-getting-a-warning-about-several-instances-of-module-on-the-page

**Comment by jxnblk** [comment] 2018-06-11 00:10
Closing this out since I suspect this is an issue with styled-components as mentioned above

**Closed by jxnblk** 2018-06-11 00:10 UTC

**Comment by empireofryan** [comment] 2018-09-05 17:03
The problem is beyond styled-components. Getting it on a fresh create-react-app,  just modified the fresh app.js like so:

`import React, { Component } from 'react';
import { Button } from '@rebass/grid';
import './App.css';

class App extends Component {
  render() {
    return (
      <div>
        <Button>
          Hi
        </Button>
      </div>
    );
  }
}

export default App;
`

Then getting this error:
![image](https://user-images.githubusercontent.com/10519553/45108956-1e3f7800-b10c-11e8-810d-9d67a86b2a1d.png)

**Comment by trabek** [comment] 2018-09-05 19:18
I have a suspicion that there is no named export "Button" in @rebass/grid. Try `import {Button} from "rebass"`

**Comment by empireofryan** [comment] 2018-09-05 19:47
Thanks @trabek that solved it!
