### ISSUE TITLE
Overriding colors messes up styles

### ISSUE THREAD

**Issue by 18thletter** [jxnblk/rebass#455] opened 2018-08-08 21:12 UTC
If you pass in a custom theme to the `Provider` component, default styles throughout this library get messed up.

I investigated, and this is because the `Provider` uses the `...` spread operator to combine the default theme with the passed in theme: https://github.com/jxnblk/rebass/blob/master/src/Provider.js#L14. Because Javascript's spread operator doesn't do a deep merge, only the first level of object keys are merged, and, as such, something like:

```javascript
<Provider theme={{colors: {}}}>
```

will completely remove colors from the theme.

To fix this, we need to do a deep object merge when merging the default theme with the passed in theme, either by writing one or using something like https://github.com/KyleAMathews/deepmerge.

I'll make this into a PR when I can figure out why Jest keeps hanging when I run `npm test`.

**Comment by jxnblk** [comment] 2018-08-09 17:34
Duplicate of #388

**Closed by jxnblk** 2018-08-09 17:34 UTC
